server:
  port: 8001

mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml       # mybatis配置文件所在路径
  type-aliases-package: com.hzit.api.bean                 # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mapper/**/*.xml                       # mapper映射文件 需要创建文件

spring:
   application:
    name: springcloud-dept						#微服务最重要的是取名字！微服务对外暴露的名字
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/rbac             # 数据库名称
    username: root
    password: root
#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  instance:
    instance-id: springcloud-dept:8001		#修改别名
    prefer-ip-address: true		#显示IP地址
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
     # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

info:
 app.name:  springcloud-dept
 company.name:  www.hzitxx.com
 build.artifactId:  ${project.artifactId}
 build.version:  ${project.version}

 #配置hystris监控中心 解决访问404
 management:
   endpoints:
     web:
       exposure:
         include: '*'